include: package:flutter_lints/flutter.yaml

linter:
  rules:
    #Errors
    - always_use_package_imports
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - unnecessary_statements

    #Style
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - avoid_catching_errors
    - avoid_final_parameters
    - avoid_unused_constructor_parameters
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - leading_newlines_in_multiline_strings
    - no_literal_bool_comparisons
    - prefer_asserts_in_initializer_lists
    - prefer_final_locals
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - use_enums